mainsite/blog_posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,SubmitField,TextAreaField
from wtforms.validators import DataRequired
from flask_wtf.file import FileField,FileAllowed

class BlogPostForm(FlaskForm):
    title=StringField('Title',validators=[DataRequired()])
    text=TextAreaField("Text",validators=[DataRequired()])
    submit=SubmitField("Post")

mainsite/blog_posts/views.py
from flask import render_template,flash,Blueprint,redirect,url_for,abort,request
from flask_login import login_required,current_user
from mainsite import db
from mainsite.models import BlogPost
from mainsite.blog_posts.forms import BlogPostForm

blog_posts=Blueprint('blog_posts',__name__)

#create
@blog_posts.route("/create",methods=['GET','POST'])
@login_required
def create_post():
    form=BlogPostForm()
    if form.validate_on_submit():
        blog_post=BlogPost(title=form.title.data,
                            text=form.text.data,
                            user_id=current_user.id)
        db.session.add(blog_post)
        db.session.commit()
        flash('You have successfully posted','post')
        return redirect(url_for('core.index'))
    return render_template('create_post.html',form=form)

#view
@blog_posts.route("/<int:blog_post_id>")
def blog_post(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html',title=blog_post.title,date=blog_post.date,post=blog_post)


#update
@blog_posts.route("/<int:blog_post_id>/update",methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author!=current_user:
        abort(403)

    form=BlogPostForm()
    if form.validate_on_submit():
        blog_post.title=form.title.data
        blog_post.text=form.text.data
        db.session.commit()
        flash('Blogpost Updated','update')
        return redirect(url_for('blog_posts.blog_post',blog_post_id=blog_post.id))

    elif request.method =='GET':
        form.title.data=blog_post.title
        form.text.data=blog_post.text

    return render_template('create_post.html',title='Updating',form=form)

@blog_posts.route("/<int:blog_post_id>/delete",methods=['GET','POST'])
@login_required
def delete_post(blog_post_id):
    blog_post=BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author!=current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('You have deleted a post','delete')
    return redirect(url_for('core.index'))

mainsite/core/views.py
from flask import render_template,request,Blueprint
from mainsite.models import BlogPost


core=Blueprint('core',__name__)

@core.route("/")
def index():
    page = request.args.get('page', 1, type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html',blog_posts=blog_posts)

@core.route("/info")
def info():
    return render_template('info.html')

mainsite/users/views.py
from flask import render_template,redirect,url_for,request,Blueprint,flash
from flask_login import login_user,logout_user,login_required,current_user
from mainsite import db
from mainsite.models import User,BlogPost
from mainsite.users.forms import LoginForm,RegisterForm,UpdateForm
from mainsite.users.picture_handler import add_profile_pic
from mainsite.static import profile_pics

users=Blueprint('users',__name__)


@users.route("/register",methods=['GET','POST'])
def register():
    form=RegisterForm()
    if form.validate_on_submit():
        user=User(email=form.email.data,
                  username=form.username.data,
                  password=form.password.data,
                  gender=form.gender.data)
        db.session.add(user)
        db.session.commit()
        flash('thanks for registration','register')
        return redirect(url_for('users.login'))
    return render_template('register.html',form=form)



@users.route("/login",methods=['GET','POST'])
def login():
    form=LoginForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()

        if user==None:
            flash("U haven't register yet",'details')
            return redirect(url_for('users.register'))

        if user.check_password(form.password.data) and user is not None:
            login_user(user)

            next=request.args.get('next')

            if next==None or not next[0]=='/':
                next=url_for('core.index')

            return redirect(next)

    return render_template('login.html',form=form)


@users.route("/logout")
def logout():
    logout_user()
    flash('you have logged out','logout')
    return redirect(url_for("core.index"))

@users.route("/account",methods=['GET','POST'])
@login_required
def account():
    form=UpdateForm()
    if form.validate_on_submit():

        if form.picture.data:
            username=current_user.username
            pic=add_profile_pic(form.picture.data,username)
            gender=form.gender.data
            current_user.profile_image=pic

        current_user.username=form.username.data
        current_user.email=form.email.data
        current_user.gender=form.gender.data
        db.session.commit()
        flash('User has been updated!','update')
        return redirect(url_for('users.account'))

    elif request.method=='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.gender.data=current_user.gender

    profile_image=url_for('static',filename='profile_pics/' +current_user.profile_image)
    return render_template('account.html',profile_image=profile_image,form=form)


@users.route("/<username>")
def user_posts(username):
    page=request.args.get('page',1,type=int)
    user=User.query.filter_by(username=username).first_or_404()
    blog_posts=BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page,per_page=5)
    return render_template('user_blog_posts.html',blog_posts=blog_posts,user=user)

mainsite/templates/account.html
{%extends 'base.html'%}
{%block content%}
<style>
  img{
    width:200px;
    height:200x;
    border-radius:50%;
  }

</style>
<div class="jumbotron">
  <div align="center">
    <!-- <h1>Welcome {{current_user.username}}</h1>
    {%if current_user.gender=='1'%}
      <img align='center' src="static/profile_pics/{{ current_user.profile_image | default('male.jpg') }}"/>
    {%elif current_user.gender=='2'%}
        <img align='center' src="static/profile_pics/{{ current_user.profile_image | default('female.jpg') }}"/> -->
      <img align='center' src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
    {%endif%}
  </div>
</div>

<div class="container">

  <form method="POST" action="" enctype="multipart/form-data">
    {{form.hidden_tag()}}
    {{form.username.label}}{{form.username(class="form-control")}}
    <br>
    <br>
    {{form.email.label}}{{form.email(class="form-control")}}
    <br>
    <br>
    {{form.picture.label}}<br>{{form.picture()}}
    <br>
    <br>
    {{form.gender.label}}<br>{{form.gender(class="form-control")}}
    <br>
    {{form.submit()}}
    <br>
    <br>
  </form>

</div>

{%endblock%}

mainsite/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <title>Venkatsagar</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{url_for('core.index')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('core.info')}}">About</a>
        </li>
        {%if current_user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.account')}}">Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('blog_posts.create_post')}}">Create Post</a>
        </li>
        {%else%}
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.login')}}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{url_for('users.register')}}">Register</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </nav>
      {%block content%}

      {%endblock%}

  </body>
</html>

mainsite/templates/blog_post.html
{% extends "base.html" %}
{% block content %}

{%with messages=get_flashed_messages(category_filter=['need'])%}
  {%for mess in messages%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
        {{mess}}
    </div>
  {%endfor%}
{%endwith%}
<div class="jumbotron">
  <h1>{{ post.title }}</h1>
  <h2>Written by:{{post.author.username}}</h2>
  <h3>Published: {{ post.date.strftime('%B %d, %Y') }}</h3>
  <br>
  <p>{{post.text}}</p>
   {% if post.author == current_user %}
     <div>
       <a class="btn btn-secondary" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#del_modal">Delete</button>
     </div>
   {% endif %}
</div>




  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Please click below</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

mainsite/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <form class="form-group" method="POST" action="" enctype="multipart/form-data">
     {{ form.hidden_tag() }}

     <div class="form-group">
     {{ form.title.label(class="form-control-label") }}
     {{ form.title(class="form-control form-control-lg ") }}
     </div>
     <div class="form-group">
     {{ form.text.label(class="form-control-label") }}
     {{ form.text(class="form-control form-control-lg") }}
     </div>
     <div class="form-group">
         {{ form.submit(class="btn btn-outline-info") }}
     </div>
  </form>

</div>

{% endblock content %}

mainsite/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Welcome to the MY-Blogger</h1>
    <ul>
      <li>A place where you can post your daily updates</li>
      <li>View other people's posts</li>
    </ul>

  </div>

  <div class="container">

    {# Go through each blog post #}
    {% for post in blog_posts.items %}

    <div class="card" >

      <div class="card-body">


        <h2><a class="card-title" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">Written By: {{ post.author.username }}</a>
        <p>Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text">{{ post.text[:100] }}...</p>
        <a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" class="btn btn-primary">Read Blog Post</a>
      </div>
    </div>

   {% endfor %}

   <nav aria-label="Page navigation example">
     <ul class="pagination justify-content-center">
       {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
          {% if blog_posts.page == page_num %}
          <li class="page-item disabled">
            <a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('core.index', page=page_num) }}">{{ page_num }}</a></li>
          {% endif %}
      {% endfor %}
    </nav>




{% endblock %}

mainsite/templates/info.html
{%extends 'base.html'%}
{%block content%}
<style>
  .git{
    border-radius:50%;
  }
  .pointing{
    border-radius:50%;
  }

</style>
<link rel="stylesheet" href="../static/info.css">
<link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet"><div id="carouselExampleControls" class="carousel slide" data-ride="carousel" style="">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="d-block w-100" src="static/pic_1.JPG/" alt="First slide">
    </div>
    <div class="carousel-item">
      <img class="d-block w-100" src="static/pic_22.JPG" alt="Second slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class="jumbotron">
  <p class=intro ><font size="5">Hi,I'm Venkat sagar. I'm a web developer and designer of this Website.

A big thanks to all of you who visited my site </font></p>
<br>
<br>
<br>


<div align=right>
  <h6>&nbsp;&nbsp;&nbsp;Front-End   :  <i>Html5,CSS3,Bootstrap4.</i></h6>
  <h6>&nbsp;&nbsp;&nbsp;Framework   :  <i>Flask(1.0.2)</i></h6>
  <h6>&nbsp;&nbsp;&nbsp;Language    :   <i>Python(3.6.5)</i>
  <h6>&nbsp;&nbsp;&nbsp;Database    : <i> SQLite3</i></h6>
  <h6>&nbsp;&nbsp;&nbsp;Deployement :  <i>Heroku</i></h6>
  <i>view source code <img class="pointing" src="static/pointing3.jpg" ></i>
  <br>
  <br>
  <a href="https://github.com/sagar12516/Blogpostsite" target="_blank"><abbr title="github.com"><img class="git" src="static/git1.jpg"></abbr></a>
</div>


</div>

{%endblock%}

mainsite/templates/login.html
{%extends 'base.html'%}
{%block content%}

{%with messages=get_flashed_messages(category_filter=['details','register'])%}
  {%for mess in messages%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      {{mess}}
  </div>
  {%endfor%}
{%endwith%}

<div class="jumbotron">
  <form  method="POST">
    {{form.hidden_tag()}}
    {{form.email.label}}{{form.email(class="form-control" ,placeholder="Enter Email")}}<br>
    {{form.password.label}}{{form.password(class="form-control" ,placeholder="Enter Password")}}<br>
    {{form.submit(class="btn btn-dark")}}

  </form>

</div>

{%endblock%}

mainsite/templates/register.html
{%extends 'base.html'%}
{%block content%}

{%with messages=get_flashed_messages(category_filter=['details','register'])%}
  {%for mess in messages%}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
      {{mess}}
  </div>
  {%endfor%}
{%endwith%}

<div class="jumbotron">
  <form  method="POST">
    {{form.hidden_tag()}}
    {{form.username.label}}{{form.username(class="form-control" ,placeholder="Enter Username")}}<br>
    {{form.email.label}}{{form.email(class="form-control" ,placeholder="Enter Email")}}<br>
    {{form.password.label}}{{form.password(class="form-control" ,placeholder="Enter Password")}}<br>
    {{form.pass_confirm.label}}{{form.pass_confirm(class="form-control" ,placeholder="Re-enter Password")}}<br>
    {{form.gender.label}}<br>
    {{form.gender(class="form-control")}}
    <br>
    {{form.submit(class="btn btn-dark")}}

  </form>

</div>

{%endblock%}

mainsite/templates/user_blog_posts.html
{% extends "base.html" %}
{% block content %}
<style>
  img{
    border-radius:50%
  }

</style>
<div class="container">
  <div class="jumbotron">
    <div align='center'>
      <h1 >Welcome to the page for {{user.username}}</h1>
      <img align='center' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}" style="width:200px">
    </div>
  </div>


{% for post in blog_posts.items %}

          <h2><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">{{ post.title }}</a></h2>
          Written by: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
          <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
          <br>
            <p>{{post.text}}</p>
          <br>

{% endfor %}


</div>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {# http://flask.pocoo.org/snippets/44/ #}

    {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
              <li class="page-item disabled">
                <a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
    {% endfor %}
</nav>
{% endblock content %}